### PR TITLE
feat(frontend): use the new demo caluma-portal-demo instead of the ar…

### PR DESCRIPTION
**Pull request by velrest**
…chived caluma-demo

### CODE REVIEW

**Comment by velrest** [comment]
@tongpu cant assign you as reviewer but feel assigned.

**Comment by hairmare** [comment]
CI is reporting the following error:
```
Failed to pull image "projectcaluma/caluma-portal-demo:release": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/projectcaluma/caluma-portal-demo:release": failed to resolve reference "docker.io/projectcaluma/caluma-portal-demo:release": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
It looks like it either has to be `docker.io/projectcaluma/caluma-demo` or you need to push the new `caluma-portal-demo` image.

**Comment by velrest** [comment]
@hairmare feel free to have a look at this again

**Review by michaelimfeld — APPROVED** [review]

**Review by eyenx — APPROVED** [review]

**Review by fujexo — APPROVED** [review]

**Comment by velrest** [comment]
@michaelimfeld @eyenx @fujexo Does one of you know what [this](https://github.com/projectcaluma/charts/runs/1655721825?check_suite_focus=true) is about?

**Comment by eyenx** [comment]
Chart-releaser, this is responsible for releaseing the chart on GH.

**Comment by eyenx** [comment]
It looks like a needed dependency repo isn't added.
 Let me take a look

**Comment by eyenx** [comment]
[this](https://github.com/projectcaluma/charts/pull/10) should fix it. 

We should also consider switching to Chart Schema version `v2` but this can be done in a feature release.

**Pull request merged**
